import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// const products = [
//   // Produtos Farmacêuticos - Medicamentos
//   {
//     title: 'Paracetamol 500mg',
//     summary: 'Analgésico e antitérmico para alívio de dores e febre',
//     description: 'Analgésico e antitérmico para alívio de dores e febre. Indicado para dores de cabeça, dores musculares e febre.',
//     brand: 'Laboratório Genérico',
//     price: 8.90,
//     last_price: 12.90,
//     stock: 150,
//     categories: ['MEDICAMENTOS', 'ANALGESICOS'],
//     images: [
//       'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop'
//     ],
//     flags: ['PRESCRICAO_MEDICA'],
//     details: {
//       principio_ativo: 'Paracetamol',
//       concentracao: '500mg',
//       apresentacao: 'Comprimidos',
//       quantidade: '20 comprimidos',
//       fabricante: 'Laboratório Genérico',
//       registro_anvisa: '123456789'
//     }
//   },
//   {
//     title: 'Ibuprofeno 600mg',
//     summary: 'Anti-inflamatório não esteroidal para alívio de dores',
//     description: 'Anti-inflamatório não esteroidal para alívio de dores, inflamações e febre. Ideal para dores articulares.',
//     brand: 'Laboratório Genérico',
//     price: 12.50,
//     last_price: 18.90,
//     stock: 120,
//     categories: ['MEDICAMENTOS', 'ANTI_INFLAMATORIOS'],
//     images: [
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop'
//     ],
//     flags: ['PRESCRICAO_MEDICA'],
//     details: {
//       principio_ativo: 'Ibuprofeno',
//       concentracao: '600mg',
//       apresentacao: 'Comprimidos',
//       quantidade: '15 comprimidos',
//       fabricante: 'Laboratório Genérico',
//       registro_anvisa: '987654321'
//     }
//   },
//   {
//     title: 'Dipirona 500mg',
//     summary: 'Analgésico e antitérmico de ação rápida',
//     description: 'Analgésico e antitérmico de ação rápida. Indicado para dores agudas e febre.',
//     brand: 'Laboratório Genérico',
//     price: 6.80,
//     last_price: 9.90,
//     stock: 200,
//     categories: ['MEDICAMENTOS', 'ANALGESICOS'],
//     images: [
//       'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop'
//     ],
//     flags: ['PRESCRICAO_MEDICA'],
//     details: {
//       principio_ativo: 'Dipirona',
//       concentracao: '500mg',
//       apresentacao: 'Comprimidos',
//       quantidade: '30 comprimidos',
//       fabricante: 'Laboratório Genérico',
//       registro_anvisa: '456789123'
//     }
//   },

//   // Produtos Hospitalares - Equipamentos
//   {
//     title: 'Estetoscópio Littmann Classic III',
//     summary: 'Estetoscópio profissional de alta qualidade',
//     description: 'Estetoscópio profissional de alta qualidade para auscultação cardíaca e pulmonar. Ideal para médicos e estudantes.',
//     brand: 'Littmann',
//     price: 299.90,
//     last_price: 399.90,
//     stock: 25,
//     categories: ['EQUIPAMENTOS', 'DIAGNOSTICO'],
//     images: [
//       'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop'
//     ],
//     flags: ['PROFISSIONAL'],
//     details: {
//       marca: 'Littmann',
//       modelo: 'Classic III',
//       material: 'Aço inoxidável',
//       peso: '180g',
//       garantia: '2 anos',
//       certificacao: 'CE'
//     }
//   },
//   {
//     title: 'Esfigmomanômetro Aneróide',
//     summary: 'Aparelho para medição de pressão arterial',
//     description: 'Aparelho para medição de pressão arterial. Preciso e durável, ideal para uso profissional.',
//     brand: 'Premium',
//     price: 189.90,
//     last_price: 249.90,
//     stock: 40,
//     categories: ['EQUIPAMENTOS', 'DIAGNOSTICO'],
//     images: [
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&h=400&fit=crop'
//     ],
//     flags: ['PROFISSIONAL'],
//     details: {
//       marca: 'Premium',
//       modelo: 'Aneróide Profissional',
//       faixa_medicao: '0-300 mmHg',
//       precisao: '±2 mmHg',
//       material: 'Metal e borracha',
//       garantia: '1 ano'
//     }
//   },
//   {
//     title: 'Termômetro Digital Infravermelho',
//     summary: 'Termômetro digital sem contato',
//     description: 'Termômetro digital sem contato para medição rápida e precisa da temperatura corporal.',
//     brand: 'TechMed',
//     price: 89.90,
//     last_price: 129.90,
//     stock: 60,
//     categories: ['EQUIPAMENTOS', 'DIAGNOSTICO'],
//     images: [
//       'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&h=400&fit=crop'
//     ],
//     flags: ['PROFISSIONAL'],
//     details: {
//       marca: 'TechMed',
//       modelo: 'InfraRed Pro',
//       faixa_medicao: '32-42°C',
//       precisao: '±0.2°C',
//       tempo_medicao: '<1 segundo',
//       bateria: '2x AAA',
//       garantia: '1 ano'
//     }
//   },

//   // Produtos Hospitalares - Consumíveis
//   {
//     title: 'Máscara N95 - Caixa com 20 unidades',
//     summary: 'Máscara de proteção respiratória N95',
//     description: 'Máscara de proteção respiratória N95. Alta eficiência de filtração para uso profissional.',
//     brand: 'SafeMask',
//     price: 45.90,
//     last_price: 69.90,
//     stock: 100,
//     categories: ['CONSUMIVEIS', 'PROTECAO'],
//     images: [
//       'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop'
//     ],
//     flags: ['PROFISSIONAL'],
//     details: {
//       marca: 'SafeMask',
//       modelo: 'N95 Profissional',
//       eficiencia_filtracao: '95%',
//       quantidade: '20 unidades',
//       material: 'Poliéster e polipropileno',
//       certificacao: 'ANVISA'
//     }
//   },
//   {
//     title: 'Luvas de Látex - Caixa com 100 unidades',
//     summary: 'Luvas descartáveis de látex natural',
//     description: 'Luvas descartáveis de látex natural. Ideais para procedimentos médicos e laboratoriais.',
//     brand: 'SafeGlove',
//     price: 32.90,
//     last_price: 49.90,
//     stock: 80,
//     categories: ['CONSUMIVEIS', 'PROTECAO'],
//     images: [
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400&h=400&fit=crop'
//     ],
//     flags: ['PROFISSIONAL'],
//     details: {
//       marca: 'SafeGlove',
//       modelo: 'Látex Natural',
//       tamanho: 'M',
//       quantidade: '100 unidades',
//       material: 'Látex natural',
//       certificacao: 'ANVISA'
//     }
//   },
//   {
//     title: 'Seringa 10ml com Agulha',
//     summary: 'Seringa descartável de 10ml com agulha',
//     description: 'Seringa descartável de 10ml com agulha. Ideal para aplicação de medicamentos.',
//     brand: 'SafeSyringe',
//     price: 2.50,
//     last_price: 3.90,
//     stock: 500,
//     categories: ['CONSUMIVEIS', 'INJETAVEIS'],
//     images: [
//       'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400&h=400&fit=crop'
//     ],
//     flags: ['PROFISSIONAL'],
//     details: {
//       marca: 'SafeSyringe',
//       modelo: '10ml com Agulha',
//       volume: '10ml',
//       agulha: '21G x 1.5"',
//       material: 'Polipropileno',
//       certificacao: 'ANVISA'
//     }
//   },

//   // Produtos Farmacêuticos - Suplementos
//   {
//     title: 'Vitamina C 1000mg',
//     summary: 'Suplemento de vitamina C de alta absorção',
//     description: 'Suplemento de vitamina C de alta absorção. Fortalece o sistema imunológico e combate radicais livres.',
//     brand: 'NutriVita',
//     price: 28.90,
//     last_price: 39.90,
//     stock: 75,
//     categories: ['SUPLEMENTOS', 'VITAMINAS'],
//     images: [
//       'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop'
//     ],
//     flags: ['NATURAL'],
//     details: {
//       principio_ativo: 'Ácido Ascórbico',
//       concentracao: '1000mg',
//       apresentacao: 'Cápsulas',
//       quantidade: '60 cápsulas',
//       fabricante: 'NutriVita',
//       registro_anvisa: '789123456'
//     }
//   },
//   {
//     title: 'Ômega 3 1000mg',
//     summary: 'Suplemento de ômega 3 de peixe de águas profundas',
//     description: 'Suplemento de ômega 3 de peixe de águas profundas. Benefícios para saúde cardiovascular e cerebral.',
//     brand: 'NutriVita',
//     price: 45.90,
//     last_price: 59.90,
//     stock: 50,
//     categories: ['SUPLEMENTOS', 'OMEGA'],
//     images: [
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop'
//     ],
//     flags: ['NATURAL'],
//     details: {
//       principio_ativo: 'Óleo de Peixe',
//       concentracao: '1000mg',
//       apresentacao: 'Cápsulas',
//       quantidade: '90 cápsulas',
//       fabricante: 'NutriVita',
//       registro_anvisa: '321654987'
//     }
//   },
//   {
//     title: 'Probiótico 10 Bilhões UFC',
//     summary: 'Suplemento probiótico com 10 bilhões de UFC',
//     description: 'Suplemento probiótico com 10 bilhões de UFC. Melhora a saúde intestinal e sistema imunológico.',
//     brand: 'NutriVita',
//     price: 38.90,
//     last_price: 49.90,
//     stock: 65,
//     categories: ['SUPLEMENTOS', 'PROBIOTICOS'],
//     images: [
//       'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
//       'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop'
//     ],
//     flags: ['NATURAL'],
//     details: {
//       principio_ativo: 'Lactobacillus e Bifidobacterium',
//       concentracao: '10 bilhões UFC',
//       apresentacao: 'Cápsulas',
//       quantidade: '30 cápsulas',
//       fabricante: 'NutriVita',
//       registro_anvisa: '147258369'
//     }
//   }
// ];

const products = [
  {
    title: "Paracetamol 500mg",
    summary: "Analgésico e antitérmico para alívio de dores e febre",
    description: "Analgésico e antitérmico para alívio de dores e febre. Indicado para dores de cabeça, dores musculares e febre.",
    brand: "Laboratório Genérico",
    price: 8.9,
    last_price: 12.9,
    stock: 150,
    categories: ["MEDICAMENTOS", "ANALGESICOS"],
    images: [
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/paracetamol.png?alt=media&token=d91ced96-0444-4545-884c-47d2d3e26980",
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/paracetamol.png?alt=media&token=d91ced96-0444-4545-884c-47d2d3e26980",
    ],
    flags: ["PRESCRICAO_MEDICA"],
    details: {
      principio_ativo: "Paracetamol",
      concentracao: "500mg",
      apresentacao: "Comprimidos",
      quantidade: "20 comprimidos",
      fabricante: "Laboratório Genérico",
      registro_anvisa: "123456789",
    },
  },
  {
    title: "Ibuprofeno 600mg",
    summary: "Analgésico e antitérmico para alívio de dores e febre",
    description: "Analgésico e antitérmico para alívio de dores e febre. Indicado para dores de cabeça, dores musculares e febre.",
    brand: "Laboratório Genérico",
    price: 12.5,
    last_price: 18.9,
    stock: 120,
    categories: ["MEDICAMENTOS", "ANTI_INFLAMATORIOS"],
    images: [
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/ibuprofeno.png?alt=media&token=2b6eab9a-c983-414c-98eb-eab60a92553e",
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/ibuprofeno.png?alt=media&token=2b6eab9a-c983-414c-98eb-eab60a92553e",
    ],
    flags: ["PRESCRICAO_MEDICA"],
    details: {
      principio_ativo: "Ibuprofeno",
      concentracao: "600mg",
      apresentacao: "Comprimidos",
      quantidade: "20 comprimidos",
      fabricante: "Laboratório Genérico",
      registro_anvisa: "1256801610013",
    },
  },
  {
    title: "Dipirona 500mg",
    summary: "NOVALGINA comprimidos 500 mg: adultos e adolescentes acima de 15 anos: 1 a 2 comprimidos até 4 vezes ao dia.",
    description: "NOVALGINA comprimidos 1 g: adultos e adolescentes acima de 15 anos: ½ a 1 comprimido até 4 vezes ao dia.",
    brand: "Novalgina",
    price: 8.9,
    last_price: 12.9,
    stock: 150,
    categories: ["MEDICAMENTOS", "ANALGESICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/dipirona.png?alt=media&token=3acc742b-1ca5-414e-adcf-51d84cfdd92c", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/dipirona.png?alt=media&token=3acc742b-1ca5-414e-adcf-51d84cfdd92c"],
    flags: ["PRESCRICAO_MEDICA"],
    details: {
      principio_ativo: "Dipirona",
      concentracao: "500mg",
      apresentacao: "Comprimidos",
      quantidade: "30 comprimidos",
      fabricante: "Laboratório Genérico",
      registro_anvisa: "1130000580256",
    },
  },
  {
    title: "Sérum Facial",
    summary: "Alta concentração de Vitamina C pura (10%) + Ácido Ferúlico.",
    description: "Protege contra os radicais livres causados pelos raios solares.",
    brand: "Skinceuticals",
    price: 399.0,
    last_price: 400.0,
    stock: 250,
    categories: ["HIGIENE PESSOAL", "COSMETICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/serum.png?alt=media&token=abad0283-ca6b-440c-a63d-f0b7584123c3", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/serum.png?alt=media&token=abad0283-ca6b-440c-a63d-f0b7584123c3"],
    flags: ["PROFISSIONAL"],
    details: {
      principio_ativo: "Vitamina C + Ácido Ferúlico",
      concentracao: "10%",
      apresentacao: "Sérum",
      quantidade: "30ml",
      fabricante: "Skinceuticals",
      registro_anvisa: "1234567890",
    },
  },
  {
    title: "Neosaldina",
    summary: "Tratamento de dores musculares e tensões.",
    description: "Tratamento de dores musculares e tensões,Liberação imediata do medicamento,Desenvolvido para potência máxima.",
    brand: "Neosaldina",
    price: 8.9,
    last_price: 12.9,
    stock: 150,
    categories: ["MEDICAMENTOS", "ANALGESICOS"],
    images: [
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/Captura%20de%20tela%202025-09-01%20015243.png?alt=media&token=932fa23e-2e10-4b19-a580-27b79d215136",
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/Captura%20de%20tela%202025-09-01%20015243.png?alt=media&token=932fa23e-2e10-4b19-a580-27b79d215136",
    ],
    flags: ["PRESCRICAO_MEDICA"],
    details: {
      principio_ativo: "Neosaldina",
      concentracao: "500mg",
      apresentacao: "Comprimidos",
      quantidade: "4 Comprimidos",
      fabricante: "Hypera",
      registro_anvisa: "123456789",
    },
  },
  {
    title: "Dorflex UNO",
    summary: "Analgésico e antitérmico de ação rápida.",
    description: "Dorflex Uno contém 1g de dipirona monoidratada, que oferece ação analgésica por até 6 horas, e é especialmente indicado para o alívio da dor associada a contraturas musculares.",
    brand: "Dorflex Uno",
    price: 8.9,
    last_price: 12.9,
    stock: 150,
    categories: ["MEDICAMENTOS", "ANALGESICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/dorflex.png?alt=media&token=4bc93589-4c14-4da0-b0f4-c5e6f3f7f8f2", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/dorflex.png?alt=media&token=4bc93589-4c14-4da0-b0f4-c5e6f3f7f8f2"],
    flags: ["PRESCRICAO_MEDICA"],
    details: {
      principio_ativo: "Dipirona Monoidratada",
      concentracao: "1G",
      apresentacao: "Comprimidos",
      quantidade: "10 comprimidos",
      fabricante: "Sanofi",
      registro_anvisa: "1130011740659",
    },
  },
  {
    title: "Arpadol",
    summary: "Indicado para quadros reumatológicos.",
    description: "Este medicamento é indicado no tratamento de quadros reumatológicos, tais como artrites e artroses, assim como no tratamento de dores lombares.",
    brand: "Arpadol",
    price: 108.99,
    last_price: 116.99,
    stock: 150,
    categories: ["MEDICAMENTOS", "ANALGESICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/arpadol.png?alt=media&token=803d0331-0f02-47b0-82b3-b578d5b2efca", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/arpadol.png?alt=media&token=803d0331-0f02-47b0-82b3-b578d5b2efca"],
    flags: ["PRESCRICAO_MEDICA"],
    details: {
      principio_ativo: "Harpagophytum Procumbens",
      concentracao: "400MG",
      apresentacao: "Comprimidos",
      quantidade: "30 Comprimidos",
      fabricante: "Apsen",
      registro_anvisa: "1011806060027",
    },
  },
  {
    title: "Creme Facial",
    summary: "Indicado para pele mista a oleosa.",
    description: "O Nivea Q10 Power é um creme facial diurno com proteção solar, projetado para combater rugas e proporcionar uma aparência rejuvenescida.",
    brand: "Nivea",
    price: 8.9,
    last_price: 12.9,
    stock: 150,
    categories: ["HIGIENE PESSOAL", "COSMETICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/creme.png?alt=media&token=4e6803d0-b970-4765-a584-fa62b446bc50", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/creme.png?alt=media&token=4e6803d0-b970-4765-a584-fa62b446bc50"],
    flags: ["PROFISSIONAL"],
    details: {
      principio_ativo: "Coenzima Q10",
      concentracao: "52mg",
      apresentacao: "Creme facial",
      quantidade: "50ml",
      fabricante: "Beiersdorf",
      registro_anvisa: "123456789",
    },
  },

  {
    title: "Loção Hidratante Facial",
    summary: "Controla a oleosidade e mantém a pele macia.",
    description: "Loção facial diária com textura leve e rápida absorção.",
    brand: "Neutrogena",
    price: 39.9,
    last_price: 49.9,
    stock: 200,
    categories: ["HIGIENE PESSOAL", "COSMETICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/locao.png?alt=media&token=94ad5f2a-df68-40ef-97fa-4c10fb10e33f", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/locao.png?alt=media&token=94ad5f2a-df68-40ef-97fa-4c10fb10e33f"],
    flags: ["PROFISSIONAL"],
    details: {
      principio_ativo: "Glicerina e Ácido Hialurônico",
      concentracao: "N/A",
      apresentacao: "Loção facial",
      quantidade: "100ml",
      fabricante: "Neutrogena",
      registro_anvisa: "123456785",
    },
  },
  {
    title: "Gel de Limpeza Facial",
    summary: "Remove impurezas e excesso de oleosidade.",
    description: "Gel facial suave, ideal para peles mistas e oleosas.",
    brand: "Vichy",
    price: 45.0,
    last_price: 55.0,
    stock: 220,
    categories: ["HIGIENE PESSOAL", "COSMETICOS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/gel.png?alt=media&token=9cfc03e4-e47a-42f7-863c-7b7a5c51596b", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/gel.png?alt=media&token=9cfc03e4-e47a-42f7-863c-7b7a5c51596b"],
    flags: ["PROFISSIONAL"],
    details: {
      principio_ativo: "Ácido Salicílico",
      concentracao: "2%",
      apresentacao: "Gel facial",
      quantidade: "150ml",
      fabricante: "Vichy",
      registro_anvisa: "123456784",
    },
  },
  {
    title: "PINÇA MICRO ADSON",
    summary: "Produto Confeccionado em Aço Inoxidável Cirúrgicos",
    description: "Plástica individual, constando os dados de identificação, procedência e rastreabilidade.",
    brand: "AGS",
    price: 299.9,
    last_price: 399.9,
    stock: 25,
    categories: ["EQUIPAMENTOS", "Pinças"],
    images: [
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/pin%C3%A7a.png?alt=media&token=c9604ed8-2114-41f7-94da-4b031fa679de",
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/pin%C3%A7a.png?alt=media&token=c9604ed8-2114-41f7-94da-4b031fa679de",
    ],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "AGS",
      modelo: "Micro Adson",
      material: "Aço inoxidável",
      peso: "15g",
      garantia: "1 ano",
      certificacao: "CE",
    },
  },
  {
    title: "Oxímetro de Pulso Digital",
    summary: "Medição precisa de oxigenação sanguínea",
    description: "Oxímetro digital de pulso para medir saturação de oxigênio e frequência cardíaca rapidamente e com precisão.",
    brand: "MedPulse",
    price: 199.9,
    last_price: 249.9,
    stock: 50,
    categories: ["EQUIPAMENTOS", "Monitoramento"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/oximetro.png?alt=media&token=29085332-3a44-4d64-aabc-8b663231512c", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/oximetro.png?alt=media&token=29085332-3a44-4d64-aabc-8b663231512c"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "MedPulse",
      modelo: "OX-200",
      material: "Plástico ABS",
      peso: "50g",
      garantia: "1 ano",
      certificacao: "CE",
    },
  },
  {
    title: "Monitor de Sinais Vitais",
    summary: "Monitor multiparâmetros para hospitais",
    description: "Monitor multiparâmetros para acompanhamento contínuo de pressão, oxigenação e frequência cardíaca de pacientes.",
    brand: "HealthTech",
    price: 2599.9,
    last_price: 2999.9,
    stock: 15,
    categories: ["EQUIPAMENTOS", "Monitoramento"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/monitor.png?alt=media&token=c1def345-f4fd-4a1a-9575-c8680a8e22e9", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/monitor.png?alt=media&token=c1def345-f4fd-4a1a-9575-c8680a8e22e9"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "HealthTech",
      modelo: "MultiParam 5000",
      material: "Plástico ABS",
      peso: "2.2kg",
      garantia: "2 anos",
      certificacao: "ANVISA",
    },
  },
  {
    title: "Bisturi Elétrico",
    summary: "Aparelho cirúrgico para cortes precisos",
    description: "Bisturi elétrico de alta performance para procedimentos cirúrgicos, com controle de intensidade e segurança.",
    brand: "MedEquip",
    price: 4599.9,
    last_price: 4999.9,
    stock: 8,
    categories: ["EQUIPAMENTOS", "Cirurgia"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/bisturi.png?alt=media&token=1aeaf8a7-42d9-4e7a-8e80-666efa7bec52", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/bisturi.png?alt=media&token=1aeaf8a7-42d9-4e7a-8e80-666efa7bec52"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "MedEquip",
      modelo: "Bisturi Elétrico 3000",
      material: "Aço inoxidável e plástico ABS",
      peso: "3.5kg",
      garantia: "2 anos",
      certificacao: "CE",
    },
  },
  {
    title: "Balança Médica Digital",
    summary: "Balança digital para uso clínico",
    description: "Balança digital de precisão para medição de peso de pacientes, com capacidade de até 200kg e display LCD.",
    brand: "HealthTech",
    price: 499.9,
    last_price: 599.9,
    stock: 20,
    categories: ["EQUIPAMENTOS", "Medidas"],
    images: [
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/balan%C3%A7a.png?alt=media&token=e01336e8-8540-4e26-bb87-4d7e97c7aca2",
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/balan%C3%A7a.png?alt=media&token=e01336e8-8540-4e26-bb87-4d7e97c7aca2",
    ],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "HealthTech",
      modelo: "BalancePro 200",
      material: "Aço inoxidável e vidro temperado",
      peso: "5kg",
      garantia: "2 anos",
      certificacao: "ANVISA",
    },
  },
  {
    title: "Termômetro Digital Infravermelho",
    summary: "Medição rápida e precisa da temperatura corporal",
    description: "Termômetro infravermelho sem contato, ideal para triagem de pacientes e uso clínico em hospitais e clínicas.",
    brand: "MediCheck",
    price: 149.9,
    last_price: 199.9,
    stock: 60,
    categories: ["EQUIPAMENTOS", "Monitoramento"],
    images: [
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/termometro.png?alt=media&token=23a86d4d-6147-4cff-915f-460680bfbb55",
      "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/termometro.png?alt=media&token=23a86d4d-6147-4cff-915f-460680bfbb55",
    ],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "MediCheck",
      modelo: "InfraTemp 500",
      material: "Plástico ABS",
      peso: "120g",
      garantia: "1 ano",
      certificacao: "CE",
    },
  },
  {
    title: "Luvas de Procedimento Descartáveis - Caixa com 100 unidades",
    summary: "Luvas de proteção para procedimentos clínicos",
    description: "Luvas descartáveis de látex, vinil ou nitrila, ideais para uso em consultórios e hospitais.",
    brand: "SafeHands",
    price: 79.9,
    last_price: 99.9,
    stock: 150,
    categories: ["CONSUMIVEIS", "PROTECAO"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/luvas.png?alt=media&token=3d9d9a3f-72ad-4b76-9bd9-652c9e3fe164", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/luvas.png?alt=media&token=3d9d9a3f-72ad-4b76-9bd9-652c9e3fe164"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "SafeHands",
      modelo: "Nitrila Plus",
      tamanho: "M",
      quantidade: "100 unidades",
      material: "Nitrila",
      certificacao: "ANVISA",
    },
  },
  {
    title: "Touca Descartável - Pacote com 50 unidades",
    summary: "Touca cirúrgica para uso hospitalar",
    description: "Touca descartável de polipropileno, indicada para uso em procedimentos médicos e odontológicos.",
    brand: "MedCap",
    price: 29.9,
    last_price: 39.9,
    stock: 200,
    categories: ["CONSUMIVEIS", "PROTECAO"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/touca.png?alt=media&token=aa96b2a6-a1c7-435e-89d8-5219b8972e1b", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/touca.png?alt=media&token=aa96b2a6-a1c7-435e-89d8-5219b8972e1b"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "MedCap",
      modelo: "Touca Cirúrgica Standard",
      quantidade: "50 unidades",
      material: "Polipropileno",
      certificacao: "ANVISA",
    },
  },
  {
    title: "Avental Cirúrgico Descartável - Pacote com 25 unidades",
    summary: "Avental de proteção para procedimentos médicos",
    description: "Avental descartável de polipropileno com proteção contra líquidos e contaminantes, ideal para hospitais e clínicas.",
    brand: "SafeWear",
    price: 119.9,
    last_price: 149.9,
    stock: 80,
    categories: ["CONSUMIVEIS", "PROTECAO"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/avental.png?alt=media&token=f8582827-4979-4d6f-a699-a534747bbeec", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/avental.png?alt=media&token=f8582827-4979-4d6f-a699-a534747bbeec"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "SafeWear",
      modelo: "Avental Protec",
      quantidade: "25 unidades",
      material: "Polipropileno",
      certificacao: "ANVISA",
    },
  },
  {
    title: "Soro Fisiológico 0,9% - Frasco 500ml",
    summary: "Solução fisiológica para hidratação e limpeza",
    description: "Soro fisiológico estéril 0,9%, indicado para limpeza de feridas, hidratação intravenosa e nebulização.",
    brand: "BioSoro",
    price: 12.9,
    last_price: 19.9,
    stock: 300,
    categories: ["CONSUMIVEIS", "SOLUCOES"],
    images: ["https://images.unsplash.com/photo-1588776814546-3d2b65a8c8d7?w=400&h=400&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop"],
    flags: ["PROFISSIONAL"],
    details: {
      marca: "BioSoro",
      modelo: "Soro Fisiológico 0,9%",
      quantidade: "500ml",
      material: "Plástico PET",
      certificacao: "ANVISA",
    },
  },
  {
    title: "Ômega 3 1000mg",
    summary: "Suplemento de ômega 3 para saúde cardiovascular",
    description: "Suplemento de ômega 3 com alta concentração de EPA e DHA. Auxilia na manutenção da saúde do coração e circulação.",
    brand: "NutriVita",
    price: 59.9,
    last_price: 69.9,
    stock: 50,
    categories: ["SUPLEMENTOS", "OMEGA 3"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/omega3.png?alt=media&token=0790afcb-b839-4c85-94d9-bad1873116b2", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/omega3.png?alt=media&token=0790afcb-b839-4c85-94d9-bad1873116b2"],
    flags: ["NATURAL"],
    details: {
      principio_ativo: "Óleo de Peixe",
      concentracao: "1000mg",
      apresentacao: "Cápsulas",
      quantidade: "60 cápsulas",
      fabricante: "NutriVita",
      registro_anvisa: "789123457",
    },
  },
  {
    title: "Magnésio 400mg",
    summary: "Suplemento de magnésio para fortalecimento muscular",
    description: "Suplemento de magnésio quelato, auxilia na função muscular e na redução da fadiga.",
    brand: "Oficial farma",
    price: 34.9,
    last_price: 44.9,
    stock: 80,
    categories: ["SUPLEMENTOS", "MINERAIS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/oficial.png?alt=media&token=c9b5e466-c73f-4ba1-9d49-8c48d202e850", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/oficial.png?alt=media&token=c9b5e466-c73f-4ba1-9d49-8c48d202e850"],
    flags: ["NATURAL"],
    details: {
      principio_ativo: "Magnésio Quelato",
      concentracao: "400mg",
      apresentacao: "Cápsulas",
      quantidade: "60 cápsulas",
      fabricante: "BioMag",
      registro_anvisa: "789123458",
    },
  },
  {
    title: "Vitamina D3 2000UI",
    summary: "Suplemento de vitamina D para ossos e imunidade",
    description: "Vitamina D3 em cápsulas, auxilia na absorção de cálcio e no fortalecimento do sistema imunológico.",
    brand: "Oficial farma",
    price: 29.9,
    last_price: 39.9,
    stock: 90,
    categories: ["SUPLEMENTOS", "VITAMINAS"],
    images: ["https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/d3.png?alt=media&token=474e6f3b-9e5e-4565-89cb-3b79ca1d0374", "https://firebasestorage.googleapis.com/v0/b/snackfast-6ef93.appspot.com/o/d3.png?alt=media&token=474e6f3b-9e5e-4565-89cb-3b79ca1d0374"],
    flags: ["NATURAL"],
    details: {
      principio_ativo: "Colecalciferol",
      concentracao: "2000UI",
      apresentacao: "Cápsulas",
      quantidade: "60 cápsulas",
      fabricante: "NutriSun",
      registro_anvisa: "789123459",
    },
  },
];
export async function seedProducts() {
  try {
    await prisma.product.deleteMany();
    for (const product of products) {
      await prisma.product.create({
        data: {
          title: product.title,
          summary: product.summary,
          description: product.description,
          brand: product.brand,
          price: product.price,
          last_price: product.last_price,
          stock: product.stock,
          categories: product.categories,
          images: product.images,
          flags: product.flags,
          details: product.details
        }
      });
    }
    console.log(`✅ ${products.length} produtos criados com sucesso!`);
  } catch (error) {
    throw error;
  }
}
