version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge

